### ISSUE TITLE
__setitem__ for array element not working.

### ISSUE THREAD

**Issue by ONLYstcm** [russellromney/brain-plasma#18]
Updating a single value of an array doesn't seem to work. For example:

```
brain['data'] = [2, 45, 7, 8]                                                                                                 

In [4]: print(brain['data'])                                                                                                          
[2, 45, 7, 8]

In [5]: brain['data'][0] = 5                                                                                                          

In [6]: print(brain['data'])                                                                                                          
[2, 45, 7, 8]

In [7]: brain['data'][1] = 5                                                                                                          

In [8]: print(brain['data'])                                                                                                          
[2, 45, 7, 8]   
```

**Comment by russellromney** [comment]
Sorry for delay. 

This is as expected - `__setitem__` changes the entire item in Plasma. `brain-plasma` does not support indexing or assignment within __setitem__.

You'd need to:
```
temp = brain['data']
data[0] = 5
brain['data'] = 5
```

I'm sure there are interesting ways to solve this with properties and making stored objects classes...but I don't know how to do that. Would love help/links.

**Comment by tcbegley** [comment]
I've thought about this a bit, and I think it's probably not going to be possible to support. First though, let me explain the issue as I understand it. First note that

```python
# this
brain["data"][0] = 5

# is the same as
tmp["data"]
tmp[0] = 5
```

as @russellromney already pointed out. If `brain` is a Python dictionary of lists, then `brain["data"]` returns a reference to the actual list that is in memory, so modifying an entry modifies what is stored in the dictionary. If `brain` is a `brain_plasma.Brain` object, then there is no list already in memory, so there's nothing to return a reference to. Instead data is pulled from the plasma store, a list is created and returned. You no longer have two references to the same object, you have two copies of the same data, and modifying one does not affect the other.

The only way to change that would be if `Brain` stores references to the objects it has returned, then writes them back to the plasma store when it goes out of scope, or when the user makes an explicit call to a flush method or something so that the copies stay in sync. Apart from that being hard to implement, I think it would cause all sorts of issues with unintended updates and clashes when you have concurrent users. For example, if `brain["data"][0] = 5` did modify data in the plasma store, then so would something like this

```python
data = brain["data"]
first_item = data.pop(0)
```

and in that case it's much less obvious that the user intended to modify the underlying data. I think it's much better to force the user to be explicit in their intentions by writing separate lines for "get", "modify" and "write".

For reference, the analogous thing doesn't work either with `pandas.HDFStore` which is sort of similar to `brain_plasma.Brain`

```python
import pandas as pd

s = pd.Series([0, 1, 2])
store = pd.HDFStore("store.h5")

store["data"] = s
store["data"][0] = 10
store["data"]
```

the last line returns

```
0    0
1    1
2    2
dtype: int64
```

**Comment by russellromney** [comment]
I theorized some ways to do this by storing all objects as trees of reference objects, each having a type, value, plasma.ObjectID, and optional parents and children. Editing and assignment could be done sequentially and referentially with some kind of conversion/combination algorithm supporting various object types. However as @tcbegley pointed out, that would be very fragile with concurrent users. `brain`
 is already not ACID compliant, so introducing fragility won't help.

>  I think it's much better to force the user to be explicit in their intentions by writing separate lines for "get", "modify" and "write".

That's along the lines of what I was thinking. Thanks for the input. Good issue to think about. Closing.
